# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main  # Trigger on push to main branch

# jobs:
#   docker:
#     runs-on: ubuntu-latest

#     steps:
#       # 1. Checkout code
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # 2. Log in to Docker Hub
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # 3. Build Docker image
#       - name: Build Docker image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/node-api-boilerplate:latest .

#       # 4. Push Docker image to Docker Hub
#       - name: Push Docker image
#         run: |
#           docker push ${{ secrets.DOCKER_USERNAME }}/node-api-boilerplate:latest

name: Deploy API

on:
  push:
    branches:
      - main   # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /Node-Boilerplate   # path to your project
            git pull origin main
            npm install --production
            pm2 restart Nodeboilerplate
